[package]
name = "rusting"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "A terminal API client for organizing and sending HTTP requests"
homepage = "https://github.com/sg004baa/rusting"

[lints]
workspace = true

[dependencies]
rusting-core.workspace = true
rusting-openapi.workspace = true
rusting-tui.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true

[[bin]]
name = "rusting"
path = "src/main.rs"
